### ISSUE TITLE
Self language is not related to Lisp

### ISSUE THREAD

**Issue by piotrklibert** [bebraw/survive-js#27]
In section 1.1:

> These languages are a variant of Lisp known as Scheme and Self.

Ok for Scheme, but Self has very little to do with Lisps. Instead it's heavily inspired by Smalltalk, another ancient ('72) language which is "pure OO". There are many object systems for various Lisps, including the most well known CLOS, but they were added to them later, while Smalltalk (and Self) was designed with objects in mind from the very beginning.

**Comment by bebraw** [comment]
Yeah, very good point! I'll reword that.
